import React from 'react'

export default function Home() {
  return (
    <div className='section space-y-4'>
      {/* home page with tons of content */}
      <h1 className='text-3xl'>Home Page</h1>
      <p className='text-lg'>This is the home page</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quasi, eos! Illo minus sit corporis reiciendis, molestias quidem, similique veritatis exercitationem provident, repellat expedita culpa id tenetur placeat officia tempore. Architecto minima accusamus saepe veritatis voluptatem quo qui assumenda, labore consequuntur quam, culpa nisi ipsum cupiditate facere fuga aliquam laudantium, libero sapiente voluptate? Eligendi odio cumque aliquam fuga unde voluptatibus eos saepe? Deserunt voluptatibus laudantium nam voluptas eos accusamus est animi velit modi ad praesentium ipsam saepe reprehenderit aliquid aliquam molestias nulla quo provident, distinctio in vero incidunt voluptates? Et, dolor libero? Unde veritatis aspernatur vel ut quae assumenda laborum tenetur.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quasi, eos! Illo minus sit corporis reiciendis, molestias quidem, similique veritatis exercitationem provident, repellat expedita culpa id tenetur placeat officia tempore. Architecto minima accusamus saepe veritatis voluptatem quo qui assumenda, labore consequuntur quam, culpa nisi ipsum cupiditate facere fuga aliquam laudantium, libero sapiente voluptate? Eligendi odio cumque aliquam fuga unde voluptatibus eos saepe? Deserunt voluptatibus laudantium nam voluptas eos accusamus est animi velit modi ad praesentium ipsam saepe reprehenderit aliquid aliquam molestias nulla quo provident, distinctio in vero incidunt voluptates? Et, dolor libero? Unde veritatis aspernatur vel ut quae assumenda laborum tenetur.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quasi, eos! Illo minus sit corporis reiciendis, molestias quidem, similique veritatis exercitationem provident, repellat expedita culpa id tenetur placeat officia tempore. Architecto minima accusamus saepe veritatis voluptatem quo qui assumenda, labore consequuntur quam, culpa nisi ipsum cupiditate facere fuga aliquam laudantium, libero sapiente voluptate? Eligendi odio cumque aliquam fuga unde voluptatibus eos saepe? Deserunt voluptatibus laudantium nam voluptas eos accusamus est animi velit modi ad praesentium ipsam saepe reprehenderit aliquid aliquam molestias nulla quo provident, distinctio in vero incidunt voluptates? Et, dolor libero? Unde veritatis aspernatur vel ut quae assumenda laborum tenetur.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quasi, eos! Illo minus sit corporis reiciendis, molestias quidem, similique veritatis exercitationem provident, repellat expedita culpa id tenetur placeat officia tempore. Architecto minima accusamus saepe veritatis voluptatem quo qui assumenda, labore consequuntur quam, culpa nisi ipsum cupiditate facere fuga aliquam laudantium, libero sapiente voluptate? Eligendi odio cumque aliquam fuga unde voluptatibus eos saepe? Deserunt voluptatibus laudantium nam voluptas eos accusamus est animi velit modi ad praesentium ipsam saepe reprehenderit aliquid aliquam molestias nulla quo provident, distinctio in vero incidunt voluptates? Et, dolor libero? Unde veritatis aspernatur vel ut quae assumenda laborum tenetur.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quasi, eos! Illo minus sit corporis reiciendis, molestias quidem, similique veritatis exercitationem provident, repellat expedita culpa id tenetur placeat officia tempore. Architecto minima accusamus saepe veritatis voluptatem quo qui assumenda, labore consequuntur quam, culpa nisi ipsum cupiditate facere fuga aliquam laudantium, libero sapiente voluptate? Eligendi odio cumque aliquam fuga unde voluptatibus eos saepe? Deserunt voluptatibus laudantium nam voluptas eos accusamus est animi velit modi ad praesentium ipsam saepe reprehenderit aliquid aliquam molestias nulla quo provident, distinctio in vero incidunt voluptates? Et, dolor libero? Unde veritatis aspernatur vel ut quae assumenda laborum tenetur.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quasi, eos! Illo minus sit corporis reiciendis, molestias quidem, similique veritatis exercitationem provident, repellat expedita culpa id tenetur placeat officia tempore. Architecto minima accusamus saepe veritatis voluptatem quo qui assumenda, labore consequuntur quam, culpa nisi ipsum cupiditate facere fuga aliquam laudantium, libero sapiente voluptate? Eligendi odio cumque aliquam fuga unde voluptatibus eos saepe? Deserunt voluptatibus laudantium nam voluptas eos accusamus est animi velit modi ad praesentium ipsam saepe reprehenderit aliquid aliquam molestias nulla quo provident, distinctio in vero incidunt voluptates? Et, dolor libero? Unde veritatis aspernatur vel ut quae assumenda laborum tenetur.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quasi, eos! Illo minus sit corporis reiciendis, molestias quidem, similique veritatis exercitationem provident, repellat expedita culpa id tenetur placeat officia tempore. Architecto minima accusamus saepe veritatis voluptatem quo qui assumenda, labore consequuntur quam, culpa nisi ipsum cupiditate facere fuga aliquam laudantium, libero sapiente voluptate? Eligendi odio cumque aliquam fuga unde voluptatibus eos saepe? Deserunt voluptatibus laudantium nam voluptas eos accusamus est animi velit modi ad praesentium ipsam saepe reprehenderit aliquid aliquam molestias nulla quo provident, distinctio in vero incidunt voluptates? Et, dolor libero? Unde veritatis aspernatur vel ut quae assumenda laborum tenetur.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quasi, eos! Illo minus sit corporis reiciendis, molestias quidem, similique veritatis exercitationem provident, repellat expedita culpa id tenetur placeat officia tempore. Architecto minima accusamus saepe veritatis voluptatem quo qui assumenda, labore consequuntur quam, culpa nisi ipsum cupiditate facere fuga aliquam laudantium, libero sapiente voluptate? Eligendi odio cumque aliquam fuga unde voluptatibus eos saepe? Deserunt voluptatibus laudantium nam voluptas eos accusamus est animi velit modi ad praesentium ipsam saepe reprehenderit aliquid aliquam molestias nulla quo provident, distinctio in vero incidunt voluptates? Et, dolor libero? Unde veritatis aspernatur vel ut quae assumenda laborum tenetur.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quasi, eos! Illo minus sit corporis reiciendis, molestias quidem, similique veritatis exercitationem provident, repellat expedita culpa id tenetur placeat officia tempore. Architecto minima accusamus saepe veritatis voluptatem quo qui assumenda, labore consequuntur quam, culpa nisi ipsum cupiditate facere fuga aliquam laudantium, libero sapiente voluptate? Eligendi odio cumque aliquam fuga unde voluptatibus eos saepe? Deserunt voluptatibus laudantium nam voluptas eos accusamus est animi velit modi ad praesentium ipsam saepe reprehenderit aliquid aliquam molestias nulla quo provident, distinctio in vero incidunt voluptates? Et, dolor libero? Unde veritatis aspernatur vel ut quae assumenda laborum tenetur.</p>
    </div>
  )
}
